/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2024-09-25 05:45:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("        \r\n");
      out.write("                        번호 아이디 이름 카테고리 스킨 목록수 페이지수 파일첨부 코멘트 답글 수정/삭제\r\n");
      out.write("						<table class=\"table table-bordered comtable\">\r\n");
      out.write("							<colgroup>\r\n");
      out.write("								<col>\r\n");
      out.write("								<col>\r\n");
      out.write("								<col>\r\n");
      out.write("								<col>\r\n");
      out.write("								<col>\r\n");
      out.write("								<col>\r\n");
      out.write("								<col>\r\n");
      out.write("								<col>\r\n");
      out.write("								<col>\r\n");
      out.write("								<col>\r\n");
      out.write("								<col>\r\n");
      out.write("							</colgroup>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th>#</th>\r\n");
      out.write("								<th>이름</th>\r\n");
      out.write("								<th>카테고리</th>\r\n");
      out.write("								<th>스킨</th>\r\n");
      out.write("								<th>목록수</th>\r\n");
      out.write("								<th>페이지수</th>\r\n");
      out.write("								<th>파일첨부</th>\r\n");
      out.write("								<th>코멘트</th>\r\n");
      out.write("								<th>답글</th>\r\n");
      out.write("								<th>삭제/수정</th>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<!-- loop -->\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td>1</td>\r\n");
      out.write("								<td>\r\n");
      out.write("									<input type=\"text\" name=\"title\"  class=\"title\" value=\"공지사항\"/>\r\n");
      out.write("								</td>\r\n");
      out.write("								<td>\r\n");
      out.write("									<select name=\"category\">\r\n");
      out.write("										<option value=\"n\">없음</option>\r\n");
      out.write("										<option value=\"y\">있음</option>\r\n");
      out.write("									</select>\r\n");
      out.write("								</td>\r\n");
      out.write("								<td>\r\n");
      out.write("									<select name=\"skin\">\r\n");
      out.write("										<option value=\"1\">목록형</option>\r\n");
      out.write("										<option value=\"2\">갤러리</option>\r\n");
      out.write("										<option value=\"3\">기사형</option>\r\n");
      out.write("										<option value=\"4\">블로그형</option>\r\n");
      out.write("									</select>\r\n");
      out.write("								</td>\r\n");
      out.write("								<td>\r\n");
      out.write("									<input type=\"text\" name=\"listCount\" value=\"15\" />\r\n");
      out.write("								</td>\r\n");
      out.write("								<td>\r\n");
      out.write("									<input type=\"text\" name=\"pageCount\" value=\"15\" />\r\n");
      out.write("								</td>\r\n");
      out.write("								<td>\r\n");
      out.write("									<select name=\"file\">\r\n");
      out.write("										<option value=\"n\">no</option>\r\n");
      out.write("										<option value=\"y\">yes</option>\r\n");
      out.write("									</select>\r\n");
      out.write("								</td>\r\n");
      out.write("								<td>\r\n");
      out.write("									<select name=\"comment\">\r\n");
      out.write("										<option value=\"n\">no</option>\r\n");
      out.write("										<option value=\"y\">yes</option>\r\n");
      out.write("									</select>\r\n");
      out.write("								</td>\r\n");
      out.write("								<td>\r\n");
      out.write("									<select name=\"rewirte\">\r\n");
      out.write("										<option value=\"n\">no</option>\r\n");
      out.write("										<option value=\"y\">yes</option>\r\n");
      out.write("									</select>\r\n");
      out.write("								</td>\r\n");
      out.write("								<td>\r\n");
      out.write("									<a href=\"#\" data-num=\"1\" class=\"del-board\">삭제</a>\r\n");
      out.write("									<a href=\"#\" data-num=\"1\" class=\"edt-board\">수정</a>\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<!-- /loop -->\r\n");
      out.write("						</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("           \r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
